<?php
// backend/api/admin/admin.php

function mdAdminRequireOperator(): ApiSession {
    $auth = DbhAuth::begin();
    $auth->fetchSessionData();
    mdAuthEnsureClientMetadata($auth);

    if (!canUserCreateCompany($auth->getLogin(), $auth)) {
        throw new ApiError('PERMISSION_DENIED', 'Keine Betreiber-Berechtigung fuer das Admin-Panel');
    }

    return $auth;
}

function mdAdminEnsureSchema(ApiSession $auth): void {
    mdAuthEnsureClientMetadata($auth);
    $auth->execute("
        CREATE TABLE IF NOT EXISTS auth.user_config (
            user_id integer NOT NULL REFERENCES auth.\"user\"(id) ON DELETE CASCADE,
            cfg_key text NOT NULL,
            cfg_value text,
            PRIMARY KEY (user_id, cfg_key)
        )
    ");
    $auth->execute("
        CREATE TABLE IF NOT EXISTS auth.admin_invites (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            client_id integer REFERENCES auth.clients(id) ON DELETE CASCADE,
            email text NOT NULL,
            login text,
            name text,
            role text NOT NULL DEFAULT 'company_admin',
            status text NOT NULL DEFAULT 'pending',
            token_hash text NOT NULL UNIQUE,
            setup_allowed boolean NOT NULL DEFAULT false,
            email_sent boolean NOT NULL DEFAULT false,
            email_status text,
            invited_by_user_id integer REFERENCES auth.\"user\"(id) ON DELETE SET NULL,
            invited_by_login text,
            expires_at timestamp without time zone,
            accepted_at timestamp without time zone,
            itime timestamp without time zone NOT NULL DEFAULT now(),
            mtime timestamp without time zone
        )
    ");
    $auth->execute("CREATE INDEX IF NOT EXISTS admin_invites_client_idx ON auth.admin_invites(client_id)");
    $auth->execute("CREATE INDEX IF NOT EXISTS admin_invites_email_idx ON auth.admin_invites(lower(email))");
}

function mdAdminRequireHubAccess(): array {
    $auth = DbhAuth::begin();
    $auth->fetchSessionData();
    mdAdminEnsureSchema($auth);

    $isOperator = canUserCreateCompany($auth->getLogin(), $auth);
    $canManageCurrentCompany = $isOperator || $auth->checkPermissions(['admin'], false);

    if (!$canManageCurrentCompany) {
        throw new ApiError('PERMISSION_DENIED', 'Keine Berechtigung fuer das Admin-Panel');
    }

    return [
        'auth' => $auth,
        'is_operator' => $isOperator,
        'current_client_id' => intval($auth->getClientId()),
        'login' => $auth->getLogin(),
        'can_create_company' => $isOperator,
        'can_manage_users' => true,
        'can_edit_panel_settings' => $isOperator,
    ];
}

function mdAdminCanManageClient(array $context, int $clientId): bool {
    return !empty($context['is_operator']) || intval($context['current_client_id']) === $clientId;
}

function mdAdminRequireClientAccess(array $context, int $clientId): void {
    if (!mdAdminCanManageClient($context, $clientId)) {
        throw new ApiError('PERMISSION_DENIED', 'Keine Berechtigung fuer dieses Firmenpanel');
    }
}

function mdAdminBool($value): bool {
    return $value === true || $value === 1 || $value === '1' || $value === 'true' || $value === 't' || $value === 'on';
}

function mdAdminBoolValue($value): string {
    return mdAdminBool($value) ? 't' : 'f';
}

function mdAdminUserConfig(ApiSession $auth, int $userId): array {
    $rows = $auth->getAll(
        'SELECT cfg_key, cfg_value FROM auth.user_config WHERE user_id = :user_id',
        [':user_id' => $userId]
    );
    $config = [];
    foreach ($rows as $row) {
        $config[$row['cfg_key']] = $row['cfg_value'];
    }
    return $config;
}

function mdAdminSaveUserConfig(ApiSession $auth, int $userId, string $key, string $value): void {
    $auth->execute(
        'INSERT INTO auth.user_config (user_id, cfg_key, cfg_value)
         VALUES (:user_id, :cfg_key, :cfg_value)
         ON CONFLICT (user_id, cfg_key) DO UPDATE SET cfg_value = EXCLUDED.cfg_value',
        [
            ':user_id' => $userId,
            ':cfg_key' => $key,
            ':cfg_value' => $value,
        ]
    );
}

function mdAdminOperatorProfile(ApiSession $auth): array {
    $userId = intval($auth->getUserId());
    $user = $auth->getOne(
        'SELECT id, login, name, email
         FROM auth."user"
         WHERE id = :id',
        [':id' => $userId]
    );
    if (!$user) {
        throw new ApiError('USER_NOT_FOUND', 'Benutzer wurde nicht gefunden');
    }

    $config = mdAdminUserConfig($auth, $userId);
    return [
        'id' => intval($user['id']),
        'login' => $user['login'],
        'name' => $user['name'] ?? '',
        'email' => $user['email'] ?? '',
        'theme_mode' => in_array(($config['theme_mode'] ?? 'light'), ['light', 'dark', 'system'], true)
            ? $config['theme_mode']
            : 'light',
        'admin_debug' => mdAdminBool($config['admin_debug'] ?? false),
    ];
}

function mdAdminClientDefaults(ApiSession $auth, int $clientId): array {
    try {
        $company = mdAdminCompanyDbForClient($auth, $clientId);
        $rows = $company->getAll(
            "SELECT key, value
             FROM defaults_oserp
             WHERE key IN ('debug', 'company_name', 'email_smtp_host', 'email_username', 'email_address')"
        );
    } catch (\Throwable $e) {
        return [
            'debug_enabled' => false,
            'smtp_configured' => false,
            'health' => 'database_error',
            'health_error' => $e->getMessage(),
        ];
    }

    $defaults = [];
    foreach ($rows as $row) {
        $defaults[$row['key']] = $row['value'];
    }
    return [
        'debug_enabled' => mdAdminBool($defaults['debug'] ?? false),
        'smtp_configured' => !empty($defaults['email_smtp_host']) && (!empty($defaults['email_username']) || !empty($defaults['email_address'])),
        'health' => 'ok',
        'health_error' => '',
    ];
}

function mdAdminReadTail(string $path, int $maxBytes = 160000): array {
    if ($path === '' || !file_exists($path)) {
        return [
            'available' => false,
            'message' => 'Logdatei wurde noch nicht gefunden.',
            'path' => $path,
            'content' => '',
        ];
    }
    if (!is_readable($path)) {
        return [
            'available' => false,
            'message' => 'Logdatei ist fuer die Web-App nicht lesbar.',
            'path' => $path,
            'content' => '',
        ];
    }

    $size = filesize($path) ?: 0;
    $handle = fopen($path, 'rb');
    if (!$handle) {
        return [
            'available' => false,
            'message' => 'Logdatei konnte nicht geoeffnet werden.',
            'path' => $path,
            'content' => '',
        ];
    }
    if ($size > $maxBytes) {
        fseek($handle, -$maxBytes, SEEK_END);
    }
    $content = stream_get_contents($handle);
    fclose($handle);

    return [
        'available' => true,
        'message' => $size > $maxBytes ? 'Letzte Logzeilen geladen.' : 'Log geladen.',
        'path' => $path,
        'content' => $content ?: '',
    ];
}

function mdAdminSlugLogin(string $value): string {
    if (function_exists('iconv')) {
        $value = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $value) ?: $value;
    }
    $value = strtolower($value);
    $value = preg_replace('/[^a-z0-9._-]+/', '.', $value);
    $value = trim($value, '.-_');
    return $value ?: 'admin';
}

function mdAdminUniqueLogin(ApiSession $auth, string $preferredLogin, ?int $existingUserId = null): string {
    $base = mdAdminSlugLogin($preferredLogin);
    $login = $base;
    $suffix = 2;

    while (true) {
        $row = $auth->getOne('SELECT id FROM auth."user" WHERE login = :login', [':login' => $login]);
        if (!$row || ($existingUserId && intval($row['id']) === $existingUserId)) {
            return $login;
        }
        $login = $base . $suffix;
        $suffix++;
    }
}

function mdAdminGeneratePassword(): string {
    $alphabet = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789';
    $password = '';
    for ($i = 0; $i < 18; $i++) {
        $password .= $alphabet[random_int(0, strlen($alphabet) - 1)];
    }
    return $password;
}

function mdAdminPanelUrl(): string {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    $scheme = $https ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? '';
    return $host ? $scheme . '://' . $host . '/admin.html' : '/admin.html';
}

function mdAdminClientConnection(ApiSession $auth, int $clientId): array {
    $client = $auth->getOne(
        'SELECT id, name, company_number, dbhost, dbport, dbname, dbuser, dbpasswd,
                master_data_locked, verification_status, setup_status
         FROM auth.clients
         WHERE id = :id
           AND COALESCE(is_system, false) = false',
        [':id' => $clientId]
    );
    if (!$client) {
        throw new ApiError('CLIENT_NOT_FOUND', 'Firma wurde nicht gefunden');
    }
    return $client;
}

function mdAdminCompanyDbForClient(ApiSession $auth, int $clientId): ApiDatabase {
    $client = mdAdminClientConnection($auth, $clientId);
    return new ApiDatabase(connectPDO($client['dbhost'], $client['dbport'], $client['dbname'], $client['dbuser'], $client['dbpasswd']));
}

function mdAdminEnsureEmployee(ApiDatabase $company, string $login, string $name, string $email): void {
    $company->execute(
        "INSERT INTO employee (login, name, sales, deleted, deleted_email, itime)
         VALUES (:login, :name, true, false, :email, now())
         ON CONFLICT (login) DO UPDATE SET
             name = COALESCE(NULLIF(:name_update, ''), employee.name),
             deleted = false,
             sales = true,
             deleted_email = COALESCE(NULLIF(:email_update, ''), employee.deleted_email),
             mtime = now()",
        [
            ':login' => $login,
            ':name' => $name ?: $login,
            ':email' => $email,
            ':name_update' => $name,
            ':email_update' => $email,
        ]
    );
}

function mdAdminEnsureGroup(ApiSession $auth, int $clientId, int $userId, string $role): string {
    $groupName = match ($role) {
        'setup_agent' => 'Setup-Mitarbeiter',
        'company_user' => 'Benutzer',
        default => 'Administratoren',
    };
    $group = $auth->getOne(
        'INSERT INTO auth."group" (name, mtime)
         VALUES (:name, now())
         ON CONFLICT (name) DO UPDATE SET mtime = now()
         RETURNING id',
        [':name' => $groupName]
    );
    $groupId = intval($group['id']);

    $auth->execute(
        'INSERT INTO auth.clients_groups (client_id, group_id) VALUES (:client_id, :group_id)
         ON CONFLICT DO NOTHING',
        [':client_id' => $clientId, ':group_id' => $groupId]
    );
    $auth->execute(
        'INSERT INTO auth.user_group (user_id, group_id) VALUES (:user_id, :group_id)
         ON CONFLICT DO NOTHING',
        [':user_id' => $userId, ':group_id' => $groupId]
    );

    $rights = $role === 'company_user'
        ? [
            'customer_vendor_edit',
            'invoice_edit',
            'sales_order_edit',
            'sales_quotation_edit',
            'sales_delivery_order_edit',
        ]
        : [
            'admin',
            'special_access',
            'customer_vendor_edit',
            'customer_vendor_all_edit',
            'invoice_edit',
            'sales_order_edit',
            'sales_quotation_edit',
            'sales_delivery_order_edit',
        ];
    foreach ($rights as $right) {
        $auth->execute(
            'INSERT INTO auth.group_rights (group_id, "right", granted)
             VALUES (:group_id, :right, true)
             ON CONFLICT (group_id, "right") DO UPDATE SET granted = true',
            [':group_id' => $groupId, ':right' => $right]
        );
    }

    return $groupName;
}

function mdAdminEmailConfig(ApiDatabase $company): array {
    try {
        $rows = $company->getAll("SELECT key, value FROM defaults_oserp WHERE key LIKE 'email_%'");
    } catch (\Throwable $e) {
        return [];
    }

    $config = [];
    foreach ($rows as $row) {
        $config[$row['key']] = $row['value'];
    }
    return $config;
}

function mdAdminSendInviteMail(ApiDatabase $company, array $invite, array $credentials): array {
    $config = mdAdminEmailConfig($company);
    $host = $config['email_smtp_host'] ?? '';
    $username = $config['email_username'] ?? '';
    $password = $config['email_password'] ?? '';
    if ($host === '' || $username === '' || $password === '') {
        return [
            'sent' => false,
            'status' => 'EMAIL_NOT_CONFIGURED',
            'message' => 'SMTP ist fuer diese Firma noch nicht konfiguriert.'
        ];
    }

    require_once __DIR__ . '/../email/smtp.class.php';

    $smtp = new SmtpClient(
        $host,
        intval($config['email_smtp_port'] ?? 465),
        $config['email_smtp_encryption'] ?? 'ssl',
        $username,
        $password
    );

    $fromEmail = $config['email_address'] ?? $username;
    $fromName = $config['email_from_name'] ?? 'MotorDesk';
    $roleLabel = match ($invite['role']) {
        'setup_agent' => 'Setup-Zugang',
        'company_user' => 'Benutzer-Zugang',
        default => 'Admin-Zugang',
    };
    $subject = 'MotorDesk ' . $roleLabel . ' fuer ' . $invite['client_name'];
    $bodyText = "Hallo {$invite['name']},\n\n"
        . "fuer {$invite['client_name']} wurde ein MotorDesk-Zugang angelegt.\n\n"
        . "Login: {$credentials['login']}\n"
        . "Passwort: {$credentials['password']}\n"
        . "Admin-Panel: {$credentials['admin_url']}\n\n"
        . "Bitte nach dem ersten Login das Passwort aendern.\n";
    $bodyHtml = nl2br(htmlspecialchars($bodyText, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'));

    try {
        $smtp->send(
            $fromEmail,
            $fromName,
            [['email' => $invite['email'], 'name' => $invite['name']]],
            $subject,
            $bodyHtml,
            $bodyText
        );
        return ['sent' => true, 'status' => 'SENT', 'message' => 'Einladung wurde per E-Mail verschickt.'];
    } catch (\Throwable $e) {
        return ['sent' => false, 'status' => 'SEND_FAILED', 'message' => $e->getMessage()];
    }
}

function getAdminOverview($data) {
    $context = mdAdminRequireHubAccess();
    $auth = $context['auth'];
    $clientFilters = ['COALESCE(c.is_system, false) = false'];
    if (!$context['is_operator']) {
        $clientFilters[] = 'c.id = :current_client_id';
    }
    $clientFilterSql = 'WHERE ' . implode(' AND ', $clientFilters);
    $clientParams = $context['is_operator'] ? [] : [':current_client_id' => $context['current_client_id']];

    $clients = $auth->getAll(
        'SELECT c.id AS code,
                c.name,
                c.company_number,
                c.dbname,
                c.is_default,
                c.master_data_locked,
                c.verification_status,
                c.setup_status,
                COUNT(cu.user_id) AS assigned_users
         FROM auth.clients c
         LEFT JOIN auth.clients_users cu ON cu.client_id = c.id
         ' . $clientFilterSql . '
         GROUP BY c.id, c.name, c.company_number, c.dbname, c.is_default,
                  c.master_data_locked, c.verification_status, c.setup_status
         ORDER BY c.company_number, c.name',
        $clientParams
    );

    $userFilters = ['COALESCE(c.is_system, false) = false'];
    if (!$context['is_operator']) {
        $userFilters[] = 'cu.client_id = :current_client_id';
    }
    $userFilterSql = 'WHERE ' . implode(' AND ', $userFilters);
    $userParams = $context['is_operator'] ? [] : [':current_client_id' => $context['current_client_id']];
    $users = $auth->getAll(
        'SELECT u.id,
                u.login,
                u.name,
                u.email,
                u.active,
                COUNT(DISTINCT cu.client_id) AS client_count
         FROM auth."user" u
         JOIN auth.clients_users cu ON cu.user_id = u.id
         JOIN auth.clients c ON c.id = cu.client_id
         ' . $userFilterSql . '
         GROUP BY u.id, u.login, u.name, u.email, u.active
         ORDER BY u.login',
        $userParams
    );

    $inviteFilters = ['COALESCE(c.is_system, false) = false'];
    if (!$context['is_operator']) {
        $inviteFilters[] = 'i.client_id = :current_client_id';
    }
    $inviteFilterSql = 'WHERE ' . implode(' AND ', $inviteFilters);
    $inviteParams = $context['is_operator'] ? [] : [':current_client_id' => $context['current_client_id']];
    $invites = $auth->getAll(
        'SELECT i.id,
                i.client_id,
                c.name AS client_name,
                c.company_number,
                i.email,
                i.login,
                i.name,
                i.role,
                i.status,
                i.setup_allowed,
                i.email_sent,
                i.email_status,
                i.invited_by_login,
                i.expires_at,
                i.itime
         FROM auth.admin_invites i
         LEFT JOIN auth.clients c ON c.id = i.client_id
         ' . $inviteFilterSql . '
         ORDER BY i.itime DESC
         LIMIT 50',
        $inviteParams
    );

    $clients = array_map(function ($client) use ($auth) {
        $runtime = mdAdminClientDefaults($auth, intval($client['code']));
        return array_merge($client, $runtime);
    }, $clients);

    resultInfo(true, '', [
        'clients' => $clients,
        'users' => $users,
        'invites' => $invites,
        'profile' => mdAdminOperatorProfile($auth),
        'context' => [
            'is_operator' => $context['is_operator'],
            'current_client_id' => $context['current_client_id'],
            'login' => $context['login'],
            'can_create_company' => $context['can_create_company'],
            'can_manage_users' => $context['can_manage_users'],
            'can_edit_panel_settings' => $context['can_edit_panel_settings'],
        ],
        'operator_users' => array_values(array_filter(array_map('trim', explode(',', COMPANY_ADMIN_USERS)))),
        'admin_url' => mdAdminPanelUrl(),
        'template_editor' => [
            'status' => 'planned',
            'areas' => ['invoice', 'sales_order', 'sales_quotation', 'email']
        ]
    ]);
}

function createAdminInvite($data) {
    $context = mdAdminRequireHubAccess();
    $auth = $context['auth'];

    $clientId = intval($data['client_id'] ?? 0);
    $email = strtolower(trim($data['email'] ?? ''));
    $name = trim($data['name'] ?? '');
    $role = trim($data['role'] ?? 'company_admin');
    $sendEmail = mdAdminBool($data['send_email'] ?? false);
    $resetPassword = !array_key_exists('reset_password', $data) || mdAdminBool($data['reset_password']);
    $expiresDays = max(1, min(30, intval($data['expires_days'] ?? 7)));
    $manualPassword = trim($data['password'] ?? '');

    if ($clientId <= 0) {
        throw new ApiError('CLIENT_REQUIRED', 'Bitte eine Firma auswaehlen');
    }
    mdAdminRequireClientAccess($context, $clientId);

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new ApiError('INVALID_EMAIL', 'Bitte eine gueltige E-Mail-Adresse eintragen');
    }
    if (!in_array($role, ['company_admin', 'setup_agent', 'company_user'], true)) {
        throw new ApiError('INVALID_ROLE', 'Unbekannte Admin-Rolle');
    }
    if (!$context['is_operator'] && $role !== 'company_user') {
        throw new ApiError('PERMISSION_DENIED', 'Firmen-Admins duerfen nur Benutzer fuer das eigene Panel anlegen');
    }
    if ($manualPassword !== '' && strlen($manualPassword) < 10) {
        throw new ApiError('VALIDATION_ERROR', 'Das Startpasswort muss mindestens 10 Zeichen haben');
    }

    $client = mdAdminClientConnection($auth, $clientId);
    $company = mdAdminCompanyDbForClient($auth, $clientId);
    $preferredLogin = trim($data['login'] ?? '') ?: explode('@', $email)[0];
    $existing = $auth->getOne(
        'SELECT id, login FROM auth."user" WHERE lower(email) = lower(:email) OR login = :login ORDER BY id LIMIT 1',
        [':email' => $email, ':login' => mdAdminSlugLogin($preferredLogin)]
    );
    $existingUserId = $existing ? intval($existing['id']) : null;
    $login = $existing ? $existing['login'] : mdAdminUniqueLogin($auth, $preferredLogin);
    $passwordGenerated = $manualPassword === '';
    $password = $passwordGenerated ? mdAdminGeneratePassword() : $manualPassword;
    $passwordHash = generate_password_hash($login, $password);

    if ($existingUserId) {
        $params = [
            ':id' => $existingUserId,
            ':name' => $name ?: $login,
            ':email' => $email,
        ];
        $passwordSql = '';
        if ($resetPassword) {
            $passwordSql = ', password = :password';
            $params[':password'] = $passwordHash;
        }
        $auth->execute(
            "UPDATE auth.\"user\"
             SET name = :name,
                 email = :email,
                 active = true,
                 mtime = now()
                 $passwordSql
             WHERE id = :id",
            $params
        );
        $userId = $existingUserId;
        if (!$resetPassword) {
            $password = '';
        }
    } else {
        $row = $auth->getOne(
            'INSERT INTO auth."user" (login, password, name, email, active, mtime)
             VALUES (:login, :password, :name, :email, true, now())
             RETURNING id',
            [
                ':login' => $login,
                ':password' => $passwordHash,
                ':name' => $name ?: $login,
                ':email' => $email,
            ]
        );
        $userId = intval($row['id']);
    }

    $auth->execute(
        'INSERT INTO auth.clients_users (client_id, user_id)
         VALUES (:client_id, :user_id)
         ON CONFLICT DO NOTHING',
        [':client_id' => $clientId, ':user_id' => $userId]
    );
    $groupName = mdAdminEnsureGroup($auth, $clientId, $userId, $role);
    mdAdminEnsureEmployee($company, $login, $name ?: $login, $email);

    $token = 'mdinv_' . bin2hex(random_bytes(24));
    $adminUrl = mdAdminPanelUrl();
    $inviteUrl = $adminUrl . '?invite=' . rawurlencode($token);
    $tokenHash = hash('sha256', $token);
    $expiresAt = date('Y-m-d H:i:s', time() + ($expiresDays * 86400));

    $invite = $auth->getOne(
        'INSERT INTO auth.admin_invites (
             client_id, email, login, name, role, status, token_hash, setup_allowed,
             invited_by_user_id, invited_by_login, expires_at, mtime
         )
         VALUES (
             :client_id, :email, :login, :name, :role, :status, :token_hash, :setup_allowed,
             :invited_by_user_id, :invited_by_login, :expires_at, now()
         )
         RETURNING id',
        [
            ':client_id' => $clientId,
            ':email' => $email,
            ':login' => $login,
            ':name' => $name ?: $login,
            ':role' => $role,
            ':status' => 'pending',
            ':token_hash' => $tokenHash,
            ':setup_allowed' => $role === 'setup_agent',
            ':invited_by_user_id' => intval($auth->getUserId()),
            ':invited_by_login' => $auth->getLogin(),
            ':expires_at' => $expiresAt,
        ]
    );

    $credentials = [
        'login' => $login,
        'password' => $password,
        'admin_url' => $adminUrl,
        'invite_url' => $inviteUrl,
        'password_returned_once' => true,
        'password_generated' => $passwordGenerated,
    ];
    $inviteData = [
        'id' => intval($invite['id']),
        'client_name' => $client['name'],
        'email' => $email,
        'name' => $name ?: $login,
        'role' => $role,
        'group' => $groupName,
    ];

    $delivery = ['sent' => false, 'status' => 'NOT_REQUESTED', 'message' => 'E-Mail-Versand wurde nicht angefordert.'];
    if ($sendEmail && $password !== '') {
        $delivery = mdAdminSendInviteMail($company, $inviteData, $credentials);
        $auth->execute(
            'UPDATE auth.admin_invites
             SET email_sent = :sent, email_status = :status, mtime = now()
             WHERE id = :id',
            [
                ':sent' => !empty($delivery['sent']),
                ':status' => $delivery['status'] . ': ' . $delivery['message'],
                ':id' => intval($invite['id']),
            ]
        );
    }

    resultInfo(true, 'INVITE_CREATED', [
        'invite' => $inviteData,
        'credentials' => $credentials,
        'email_delivery' => $delivery,
    ]);
}

function updateCompanyPanelSettings($data) {
    $auth = mdAdminRequireOperator();
    mdAdminEnsureSchema($auth);

    $clientId = intval($data['client_id'] ?? 0);
    if ($clientId <= 0) {
        throw new ApiError('CLIENT_REQUIRED', 'Bitte eine Firma auswaehlen');
    }

    $companyNumber = mdAuthNormalizeCompanyNumber($data['company_number'] ?? '');
    $verificationStatus = trim($data['verification_status'] ?? 'pending');
    $setupStatus = trim($data['setup_status'] ?? 'needs_review');
    $masterDataLocked = mdAdminBool($data['master_data_locked'] ?? true);
    $debugEnabled = mdAdminBool($data['debug_enabled'] ?? false);

    if (!preg_match('/^[0-9]+$/', $companyNumber) || intval($companyNumber) < 2200) {
        throw new ApiError('VALIDATION_ERROR', 'Firmennummer muss eine Zahl ab 2200 sein');
    }
    if (!in_array($verificationStatus, ['pending', 'verified', 'rejected'], true)) {
        throw new ApiError('VALIDATION_ERROR', 'Unbekannter Gewerbepruefstatus');
    }
    if (!in_array($setupStatus, ['needs_review', 'in_setup', 'ready'], true)) {
        throw new ApiError('VALIDATION_ERROR', 'Unbekannter Setupstatus');
    }

    $existingNumber = $auth->getOne(
        'SELECT id FROM auth.clients WHERE company_number = :company_number AND id <> :client_id',
        [':company_number' => $companyNumber, ':client_id' => $clientId]
    );
    if ($existingNumber) {
        throw new ApiError('COMPANY_NUMBER_EXISTS', 'Diese Firmennummer ist bereits vergeben');
    }

    $client = $auth->getOne(
        'UPDATE auth.clients
         SET company_number = :company_number,
             verification_status = :verification_status,
             setup_status = :setup_status,
             master_data_locked = :master_data_locked,
             mtime = now()
         WHERE id = :client_id
           AND COALESCE(is_system, false) = false
         RETURNING id AS code, name, company_number, dbname, is_default,
                   master_data_locked, verification_status, setup_status',
        [
            ':company_number' => $companyNumber,
            ':verification_status' => $verificationStatus,
            ':setup_status' => $setupStatus,
            ':master_data_locked' => $masterDataLocked,
            ':client_id' => $clientId,
        ]
    );
    if (!$client) {
        throw new ApiError('CLIENT_NOT_FOUND', 'Firma wurde nicht gefunden');
    }

    $company = mdAdminCompanyDbForClient($auth, $clientId);
    $company->execute(
        "INSERT INTO defaults_oserp (key, value, mtime)
         VALUES ('debug', :debug_enabled, now())
         ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, mtime = now()",
        [':debug_enabled' => mdAdminBoolValue($debugEnabled)]
    );
    $client = array_merge($client, mdAdminClientDefaults($auth, $clientId));

    resultInfo(true, 'PANEL_SETTINGS_UPDATED', ['client' => $client]);
}

function updateAdminProfile($data) {
    $context = mdAdminRequireHubAccess();
    $auth = $context['auth'];
    $userId = intval($auth->getUserId());
    $name = trim($data['name'] ?? '');
    $email = trim($data['email'] ?? '');
    $themeMode = trim($data['theme_mode'] ?? 'light');
    $adminDebug = mdAdminBool($data['admin_debug'] ?? false);

    if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new ApiError('INVALID_EMAIL', 'Bitte eine gueltige E-Mail-Adresse eintragen');
    }
    if (!in_array($themeMode, ['light', 'dark', 'system'], true)) {
        throw new ApiError('VALIDATION_ERROR', 'Unbekannter Darstellungsmodus');
    }

    $auth->execute(
        'UPDATE auth."user"
         SET name = :name,
             email = :email,
             mtime = now()
         WHERE id = :id',
        [
            ':name' => $name ?: $auth->getLogin(),
            ':email' => $email,
            ':id' => $userId,
        ]
    );
    mdAdminSaveUserConfig($auth, $userId, 'theme_mode', $themeMode);
    mdAdminSaveUserConfig($auth, $userId, 'admin_debug', mdAdminBoolValue($adminDebug));

    resultInfo(true, 'ADMIN_PROFILE_UPDATED', [
        'profile' => mdAdminOperatorProfile($auth),
    ]);
}

function getAdminLogs($data) {
    $context = mdAdminRequireHubAccess();
    $auth = $context['auth'];
    $clientId = intval($data['client_id'] ?? $context['current_client_id']);
    $channel = trim($data['channel'] ?? 'web');

    if ($clientId > 0) {
        mdAdminRequireClientAccess($context, $clientId);
    }
    if (!in_array($channel, ['web', 'database'], true)) {
        throw new ApiError('VALIDATION_ERROR', 'Unbekannter Log-Bereich');
    }

    $client = $clientId > 0 ? mdAdminClientConnection($auth, $clientId) : null;
    if ($channel === 'database') {
        $command = 'docker compose logs --tail=200 db';
        if ($client && !empty($client['dbname'])) {
            $command .= ' # Datenbank: ' . $client['dbname'];
        }
        resultInfo(true, 'DATABASE_LOG_HINT', [
            'channel' => 'database',
            'available' => false,
            'message' => 'PostgreSQL schreibt seine Logs in den Docker-Container. Aus Sicherheitsgruenden liest die Web-App diese Container-Logs noch nicht direkt.',
            'command' => $command,
            'content' => '',
        ]);
        return;
    }

    $logFile = defined('OSERP_DEBUG_LOG_FILE')
        ? OSERP_DEBUG_LOG_FILE
        : __DIR__ . '/../../log/opensource_erp.api.debug.log';
    $log = mdAdminReadTail($logFile);
    resultInfo(true, 'WEB_LOG_LOADED', array_merge($log, [
        'channel' => 'web',
    ]));
}
