<?php
// backend/api/admin/admin.php

function mdAdminRequireOperator(): ApiSession {
    $auth = DbhAuth::begin();
    $auth->fetchSessionData();

    if (!canUserCreateCompany($auth->getLogin())) {
        throw new ApiError('PERMISSION_DENIED', 'Keine Betreiber-Berechtigung fuer das Admin-Panel');
    }

    return $auth;
}

function mdAdminEnsureSchema(ApiSession $auth): void {
    $auth->execute("
        CREATE TABLE IF NOT EXISTS auth.admin_invites (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            client_id integer REFERENCES auth.clients(id) ON DELETE CASCADE,
            email text NOT NULL,
            login text,
            name text,
            role text NOT NULL DEFAULT 'company_admin',
            status text NOT NULL DEFAULT 'pending',
            token_hash text NOT NULL UNIQUE,
            setup_allowed boolean NOT NULL DEFAULT false,
            email_sent boolean NOT NULL DEFAULT false,
            email_status text,
            invited_by_user_id integer REFERENCES auth.\"user\"(id) ON DELETE SET NULL,
            invited_by_login text,
            expires_at timestamp without time zone,
            accepted_at timestamp without time zone,
            itime timestamp without time zone NOT NULL DEFAULT now(),
            mtime timestamp without time zone
        )
    ");
    $auth->execute("CREATE INDEX IF NOT EXISTS admin_invites_client_idx ON auth.admin_invites(client_id)");
    $auth->execute("CREATE INDEX IF NOT EXISTS admin_invites_email_idx ON auth.admin_invites(lower(email))");
}

function mdAdminBool($value): bool {
    return $value === true || $value === 1 || $value === '1' || $value === 'true' || $value === 't' || $value === 'on';
}

function mdAdminSlugLogin(string $value): string {
    if (function_exists('iconv')) {
        $value = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $value) ?: $value;
    }
    $value = strtolower($value);
    $value = preg_replace('/[^a-z0-9._-]+/', '.', $value);
    $value = trim($value, '.-_');
    return $value ?: 'admin';
}

function mdAdminUniqueLogin(ApiSession $auth, string $preferredLogin, ?int $existingUserId = null): string {
    $base = mdAdminSlugLogin($preferredLogin);
    $login = $base;
    $suffix = 2;

    while (true) {
        $row = $auth->getOne('SELECT id FROM auth."user" WHERE login = :login', [':login' => $login]);
        if (!$row || ($existingUserId && intval($row['id']) === $existingUserId)) {
            return $login;
        }
        $login = $base . $suffix;
        $suffix++;
    }
}

function mdAdminGeneratePassword(): string {
    $alphabet = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789';
    $password = '';
    for ($i = 0; $i < 18; $i++) {
        $password .= $alphabet[random_int(0, strlen($alphabet) - 1)];
    }
    return $password;
}

function mdAdminPanelUrl(): string {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    $scheme = $https ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? '';
    return $host ? $scheme . '://' . $host . '/admin.html' : '/admin.html';
}

function mdAdminClientConnection(ApiSession $auth, int $clientId): array {
    $client = $auth->getOne(
        'SELECT id, name, dbhost, dbport, dbname, dbuser, dbpasswd FROM auth.clients WHERE id = :id',
        [':id' => $clientId]
    );
    if (!$client) {
        throw new ApiError('CLIENT_NOT_FOUND', 'Firma wurde nicht gefunden');
    }
    return $client;
}

function mdAdminCompanyDbForClient(ApiSession $auth, int $clientId): ApiDatabase {
    $client = mdAdminClientConnection($auth, $clientId);
    return new ApiDatabase(connectPDO($client['dbhost'], $client['dbport'], $client['dbname'], $client['dbuser'], $client['dbpasswd']));
}

function mdAdminEnsureEmployee(ApiDatabase $company, string $login, string $name, string $email): void {
    $company->execute(
        "INSERT INTO employee (login, name, sales, deleted, deleted_email, itime)
         VALUES (:login, :name, true, false, :email, now())
         ON CONFLICT (login) DO UPDATE SET
             name = COALESCE(NULLIF(:name_update, ''), employee.name),
             deleted = false,
             sales = true,
             deleted_email = COALESCE(NULLIF(:email_update, ''), employee.deleted_email),
             mtime = now()",
        [
            ':login' => $login,
            ':name' => $name ?: $login,
            ':email' => $email,
            ':name_update' => $name,
            ':email_update' => $email,
        ]
    );
}

function mdAdminEnsureGroup(ApiSession $auth, int $clientId, int $userId, string $role): string {
    $groupName = $role === 'setup_agent' ? 'Setup-Mitarbeiter' : 'Administratoren';
    $group = $auth->getOne(
        'INSERT INTO auth."group" (name, mtime)
         VALUES (:name, now())
         ON CONFLICT (name) DO UPDATE SET mtime = now()
         RETURNING id',
        [':name' => $groupName]
    );
    $groupId = intval($group['id']);

    $auth->execute(
        'INSERT INTO auth.clients_groups (client_id, group_id) VALUES (:client_id, :group_id)
         ON CONFLICT DO NOTHING',
        [':client_id' => $clientId, ':group_id' => $groupId]
    );
    $auth->execute(
        'INSERT INTO auth.user_group (user_id, group_id) VALUES (:user_id, :group_id)
         ON CONFLICT DO NOTHING',
        [':user_id' => $userId, ':group_id' => $groupId]
    );

    $rights = [
        'admin',
        'special_access',
        'customer_vendor_edit',
        'customer_vendor_all_edit',
        'invoice_edit',
        'sales_order_edit',
        'sales_quotation_edit',
        'sales_delivery_order_edit',
    ];
    foreach ($rights as $right) {
        $auth->execute(
            'INSERT INTO auth.group_rights (group_id, "right", granted)
             VALUES (:group_id, :right, true)
             ON CONFLICT (group_id, "right") DO UPDATE SET granted = true',
            [':group_id' => $groupId, ':right' => $right]
        );
    }

    return $groupName;
}

function mdAdminEmailConfig(ApiDatabase $company): array {
    try {
        $rows = $company->getAll("SELECT key, value FROM defaults_oserp WHERE key LIKE 'email_%'");
    } catch (\Throwable $e) {
        return [];
    }

    $config = [];
    foreach ($rows as $row) {
        $config[$row['key']] = $row['value'];
    }
    return $config;
}

function mdAdminSendInviteMail(ApiDatabase $company, array $invite, array $credentials): array {
    $config = mdAdminEmailConfig($company);
    $host = $config['email_smtp_host'] ?? '';
    $username = $config['email_username'] ?? '';
    $password = $config['email_password'] ?? '';
    if ($host === '' || $username === '' || $password === '') {
        return [
            'sent' => false,
            'status' => 'EMAIL_NOT_CONFIGURED',
            'message' => 'SMTP ist fuer diese Firma noch nicht konfiguriert.'
        ];
    }

    require_once __DIR__ . '/../email/smtp.class.php';

    $smtp = new SmtpClient(
        $host,
        intval($config['email_smtp_port'] ?? 465),
        $config['email_smtp_encryption'] ?? 'ssl',
        $username,
        $password
    );

    $fromEmail = $config['email_address'] ?? $username;
    $fromName = $config['email_from_name'] ?? 'MotorDesk';
    $roleLabel = $invite['role'] === 'setup_agent' ? 'Setup-Zugang' : 'Admin-Zugang';
    $subject = 'MotorDesk ' . $roleLabel . ' fuer ' . $invite['client_name'];
    $bodyText = "Hallo {$invite['name']},\n\n"
        . "fuer {$invite['client_name']} wurde ein MotorDesk-Zugang angelegt.\n\n"
        . "Login: {$credentials['login']}\n"
        . "Passwort: {$credentials['password']}\n"
        . "Admin-Panel: {$credentials['admin_url']}\n\n"
        . "Bitte nach dem ersten Login das Passwort aendern.\n";
    $bodyHtml = nl2br(htmlspecialchars($bodyText, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'));

    try {
        $smtp->send(
            $fromEmail,
            $fromName,
            [['email' => $invite['email'], 'name' => $invite['name']]],
            $subject,
            $bodyHtml,
            $bodyText
        );
        return ['sent' => true, 'status' => 'SENT', 'message' => 'Einladung wurde per E-Mail verschickt.'];
    } catch (\Throwable $e) {
        return ['sent' => false, 'status' => 'SEND_FAILED', 'message' => $e->getMessage()];
    }
}

function getAdminOverview($data) {
    $auth = mdAdminRequireOperator();
    mdAdminEnsureSchema($auth);

    $clients = $auth->getAll(
        'SELECT c.id AS code,
                c.name,
                c.dbname,
                c.is_default,
                COUNT(cu.user_id) AS assigned_users
         FROM auth.clients c
         LEFT JOIN auth.clients_users cu ON cu.client_id = c.id
         GROUP BY c.id, c.name, c.dbname, c.is_default
         ORDER BY c.name'
    );

    $users = $auth->getAll(
        'SELECT u.id,
                u.login,
                u.name,
                u.email,
                u.active,
                COUNT(cu.client_id) AS client_count
         FROM auth."user" u
         LEFT JOIN auth.clients_users cu ON cu.user_id = u.id
         GROUP BY u.id, u.login, u.name, u.email, u.active
         ORDER BY u.login'
    );

    $invites = $auth->getAll(
        'SELECT i.id,
                i.client_id,
                c.name AS client_name,
                i.email,
                i.login,
                i.name,
                i.role,
                i.status,
                i.setup_allowed,
                i.email_sent,
                i.email_status,
                i.invited_by_login,
                i.expires_at,
                i.itime
         FROM auth.admin_invites i
         LEFT JOIN auth.clients c ON c.id = i.client_id
         ORDER BY i.itime DESC
         LIMIT 50'
    );

    resultInfo(true, '', [
        'clients' => $clients,
        'users' => $users,
        'invites' => $invites,
        'operator_users' => array_values(array_filter(array_map('trim', explode(',', COMPANY_ADMIN_USERS)))),
        'admin_url' => mdAdminPanelUrl(),
        'template_editor' => [
            'status' => 'planned',
            'areas' => ['invoice', 'sales_order', 'sales_quotation', 'email']
        ]
    ]);
}

function createAdminInvite($data) {
    $auth = mdAdminRequireOperator();
    mdAdminEnsureSchema($auth);

    $clientId = intval($data['client_id'] ?? 0);
    $email = strtolower(trim($data['email'] ?? ''));
    $name = trim($data['name'] ?? '');
    $role = trim($data['role'] ?? 'company_admin');
    $sendEmail = mdAdminBool($data['send_email'] ?? false);
    $resetPassword = !array_key_exists('reset_password', $data) || mdAdminBool($data['reset_password']);
    $expiresDays = max(1, min(30, intval($data['expires_days'] ?? 7)));

    if ($clientId <= 0) {
        throw new ApiError('CLIENT_REQUIRED', 'Bitte eine Firma auswaehlen');
    }
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new ApiError('INVALID_EMAIL', 'Bitte eine gueltige E-Mail-Adresse eintragen');
    }
    if (!in_array($role, ['company_admin', 'setup_agent'], true)) {
        throw new ApiError('INVALID_ROLE', 'Unbekannte Admin-Rolle');
    }

    $client = mdAdminClientConnection($auth, $clientId);
    $company = mdAdminCompanyDbForClient($auth, $clientId);
    $preferredLogin = trim($data['login'] ?? '') ?: explode('@', $email)[0];
    $existing = $auth->getOne(
        'SELECT id, login FROM auth."user" WHERE lower(email) = lower(:email) OR login = :login ORDER BY id LIMIT 1',
        [':email' => $email, ':login' => mdAdminSlugLogin($preferredLogin)]
    );
    $existingUserId = $existing ? intval($existing['id']) : null;
    $login = $existing ? $existing['login'] : mdAdminUniqueLogin($auth, $preferredLogin);
    $password = mdAdminGeneratePassword();
    $passwordHash = generate_password_hash($login, $password);

    if ($existingUserId) {
        $params = [
            ':id' => $existingUserId,
            ':name' => $name ?: $login,
            ':email' => $email,
        ];
        $passwordSql = '';
        if ($resetPassword) {
            $passwordSql = ', password = :password';
            $params[':password'] = $passwordHash;
        }
        $auth->execute(
            "UPDATE auth.\"user\"
             SET name = :name,
                 email = :email,
                 active = true,
                 mtime = now()
                 $passwordSql
             WHERE id = :id",
            $params
        );
        $userId = $existingUserId;
        if (!$resetPassword) {
            $password = '';
        }
    } else {
        $row = $auth->getOne(
            'INSERT INTO auth."user" (login, password, name, email, active, mtime)
             VALUES (:login, :password, :name, :email, true, now())
             RETURNING id',
            [
                ':login' => $login,
                ':password' => $passwordHash,
                ':name' => $name ?: $login,
                ':email' => $email,
            ]
        );
        $userId = intval($row['id']);
    }

    $auth->execute(
        'INSERT INTO auth.clients_users (client_id, user_id)
         VALUES (:client_id, :user_id)
         ON CONFLICT DO NOTHING',
        [':client_id' => $clientId, ':user_id' => $userId]
    );
    $groupName = mdAdminEnsureGroup($auth, $clientId, $userId, $role);
    mdAdminEnsureEmployee($company, $login, $name ?: $login, $email);

    $token = 'mdinv_' . bin2hex(random_bytes(24));
    $adminUrl = mdAdminPanelUrl();
    $inviteUrl = $adminUrl . '?invite=' . rawurlencode($token);
    $tokenHash = hash('sha256', $token);
    $expiresAt = date('Y-m-d H:i:s', time() + ($expiresDays * 86400));

    $invite = $auth->getOne(
        'INSERT INTO auth.admin_invites (
             client_id, email, login, name, role, status, token_hash, setup_allowed,
             invited_by_user_id, invited_by_login, expires_at, mtime
         )
         VALUES (
             :client_id, :email, :login, :name, :role, :status, :token_hash, :setup_allowed,
             :invited_by_user_id, :invited_by_login, :expires_at, now()
         )
         RETURNING id',
        [
            ':client_id' => $clientId,
            ':email' => $email,
            ':login' => $login,
            ':name' => $name ?: $login,
            ':role' => $role,
            ':status' => 'pending',
            ':token_hash' => $tokenHash,
            ':setup_allowed' => $role === 'setup_agent',
            ':invited_by_user_id' => intval($auth->getUserId()),
            ':invited_by_login' => $auth->getLogin(),
            ':expires_at' => $expiresAt,
        ]
    );

    $credentials = [
        'login' => $login,
        'password' => $password,
        'admin_url' => $adminUrl,
        'invite_url' => $inviteUrl,
        'password_returned_once' => true,
    ];
    $inviteData = [
        'id' => intval($invite['id']),
        'client_name' => $client['name'],
        'email' => $email,
        'name' => $name ?: $login,
        'role' => $role,
        'group' => $groupName,
    ];

    $delivery = ['sent' => false, 'status' => 'NOT_REQUESTED', 'message' => 'E-Mail-Versand wurde nicht angefordert.'];
    if ($sendEmail && $password !== '') {
        $delivery = mdAdminSendInviteMail($company, $inviteData, $credentials);
        $auth->execute(
            'UPDATE auth.admin_invites
             SET email_sent = :sent, email_status = :status, mtime = now()
             WHERE id = :id',
            [
                ':sent' => !empty($delivery['sent']),
                ':status' => $delivery['status'] . ': ' . $delivery['message'],
                ':id' => intval($invite['id']),
            ]
        );
    }

    resultInfo(true, 'INVITE_CREATED', [
        'invite' => $inviteData,
        'credentials' => $credentials,
        'email_delivery' => $delivery,
    ]);
}
