/**
 * Deutsche KFZ-Kennzeichen → Landkreis/Stadt Zuordnung
 * Quelle: Kraftfahrt-Bundesamt (KBA)
 */

const kennzeichenMap = new Map([
    ['A', 'Augsburg in Bayern'],
    ['AA', 'Aalen, Ostalbkreis in Baden-Württemberg'],
    ['AB', 'Aschaffenburg in Bayern'],
    ['ABG', 'Altenburger Land in Thüringen'],
    ['AC', 'Aachen in Nordrhein-Westfalen'],
    ['AE', 'Auerbach in Sachsen'],
    ['AIC', 'Aichach-Friedberg in Bayern'],
    ['AK', 'Altenkirchen/Westerwald in Rheinland-Pfalz'],
    ['AM', 'Amberg in Bayern'],
    ['AN', 'Ansbach in Bayern'],
    ['ANA', 'Annaberg in Sachsen'],
    ['ANG', 'Angermünde in Brandenburg'],
    ['ANK', 'Anklam in Mecklenburg-Vorpommern'],
    ['AÖ', 'Altötting in Bayern'],
    ['AP', 'Apolda, Weimarer Land in Thüringen'],
    ['APD', 'Apolda in Thüringen'],
    ['ARN', 'Arnstadt in Thüringen'],
    ['ART', 'Artern in Thüringen'],
    ['AS', 'Amberg-Sulzbach in Bayern'],
    ['ASL', 'Aschersleben in Sachsen-Anhalt'],
    ['ASZ', 'Aue-Schwarzenberg in Sachsen'],
    ['AT', 'Altentreptow in Mecklenburg-Vorpommern'],
    ['AU', 'Aue in Sachsen'],
    ['AUR', 'Aurich in Niedersachsen'],
    ['AW', 'Bad Neuenahr-Ahrweiler in Rheinland-Pfalz'],
    ['AZ', 'Alzey-Worms in Rheinland-Pfalz'],
    ['AZE', 'Anhalt-Zerbst in Sachsen-Anhalt'],
    ['B', 'Berlin'],
    ['BA', 'Bamberg in Bayern'],
    ['BAD', 'Baden-Baden in Baden-Württemberg'],
    ['BAR', 'Barnim in Brandenburg'],
    ['BB', 'Böblingen in Baden-Württemberg'],
    ['BBG', 'Bernburg in Sachsen-Anhalt'],
    ['BBL', 'Brandenburg, Landesregierung und Landtag'],
    ['BC', 'Biberach/Riß in Baden-Württemberg'],
    ['BD', 'Bundestag, Bundesrat, Bundesregierung'],
    ['BED', 'Brand-Erbisdorf in Sachsen'],
    ['BEL', 'Belzig in Brandenburg'],
    ['BER', 'Bernau bei Berlin in Brandenburg'],
    ['BGL', 'Berchtesgadener Land in Bayern'],
    ['BI', 'Bielefeld in Nordrhein-Westfalen'],
    ['BIR', 'Birkenfeld/Nahe in Rheinland-Pfalz'],
    ['BIT', 'Bitburg-Prüm in Rheinland-Pfalz'],
    ['BIW', 'Bischofswerda in Sachsen'],
    ['BL', 'Zollernalbkreis / Balingen in Baden-Württemberg'],
    ['BLK', 'Burgenlandkreis in Sachsen-Anhalt'],
    ['BM', 'Erftkreis / Bergheim in Nordrhein-Westfalen'],
    ['BN', 'Bonn in Nordrhein-Westfalen'],
    ['BNA', 'Borna in Sachsen'],
    ['BO', 'Bochum in Nordrhein-Westfalen'],
    ['BÖ', 'Bördekreis-Oschersleben in Sachsen-Anhalt'],
    ['BOR', 'Borken / Ahaus in Nordrhein-Westfalen'],
    ['BOT', 'Bottrop in Nordrhein-Westfalen'],
    ['BP', 'Bundespolizei'],
    ['BRA', 'Wesermarsch / Brake in Niedersachsen'],
    ['BRB', 'Brandenburg an der Havel'],
    ['BRG', 'Burg in Sachsen-Anhalt'],
    ['BS', 'Braunschweig in Niedersachsen'],
    ['BSK', 'Beeskow in Brandenburg'],
    ['BT', 'Bayreuth in Bayern'],
    ['BTF', 'Bitterfeld in Sachsen-Anhalt'],
    ['BÜS', 'Büsingen am Hochrhein in Baden-Württemberg'],
    ['BÜZ', 'Bützow in Mecklenburg-Vorpommern'],
    ['BW', 'Bundes-Wasser- und Schifffahrtsverwaltung'],
    ['BWL', 'Baden-Württemberg, Landesregierung und Landtag'],
    ['BYL', 'Bayern, Landesregierung und Landtag'],
    ['BZ', 'Bautzen in Sachsen'],
    ['C', 'Chemnitz in Sachsen'],
    ['CA', 'Calau in Brandenburg'],
    ['CB', 'Cottbus in Brandenburg'],
    ['CE', 'Celle in Niedersachsen'],
    ['CHA', 'Cham/Oberpfalz in Bayern'],
    ['CLP', 'Cloppenburg in Niedersachsen'],
    ['CO', 'Coburg in Bayern'],
    ['COC', 'Cochem-Zell/Mosel in Rheinland-Pfalz'],
    ['COE', 'Coesfeld/Westfalen in Nordrhein-Westfalen'],
    ['CUX', 'Cuxhaven in Niedersachsen'],
    ['CW', 'Calw in Baden-Württemberg'],
    ['D', 'Düsseldorf in Nordrhein-Westfalen'],
    ['DA', 'Darmstadt-Dieburg in Hessen'],
    ['DAH', 'Dachau in Bayern'],
    ['DAN', 'Lüchow-Dannenberg in Niedersachsen'],
    ['DAU', 'Daun/Eifel in Rheinland-Pfalz'],
    ['DB', 'Deutsche Bahn'],
    ['DBR', 'Bad Doberan in Mecklenburg-Vorpommern'],
    ['DD', 'Dresden in Sachsen'],
    ['DE', 'Dessau in Sachsen-Anhalt'],
    ['DEG', 'Deggendorf in Bayern'],
    ['DEL', 'Delmenhorst in Niedersachsen'],
    ['DGF', 'Dingolfing-Landau in Bayern'],
    ['DH', 'Diepholz-Syke in Niedersachsen'],
    ['DL', 'Döbeln in Sachsen'],
    ['DLG', 'Dillingen/Donau in Bayern'],
    ['DM', 'Demmin in Mecklenburg-Vorpommern'],
    ['DN', 'Düren in Nordrhein-Westfalen'],
    ['DO', 'Dortmund in Nordrhein-Westfalen'],
    ['DON', 'Donau-Ries / Donauwörth in Bayern'],
    ['DS', 'Dahme-Spreewald in Brandenburg'],
    ['DU', 'Duisburg in Nordrhein-Westfalen'],
    ['DÜW', 'Bad Dürkheim in Rheinland-Pfalz'],
    ['DW', 'Dippoldiswalde-Weißeritzkreis in Sachsen'],
    ['DZ', 'Delitzsch in Sachsen'],
    ['E', 'Essen in Nordrhein-Westfalen'],
    ['EA', 'Eisenach in Thüringen'],
    ['EB', 'Eilenburg in Sachsen'],
    ['EBE', 'Ebersberg in Bayern'],
    ['ED', 'Erding in Bayern'],
    ['EE', 'Elbe-Elster in Brandenburg'],
    ['EF', 'Erfurt in Thüringen'],
    ['EH', 'Eisenhüttenstadt in Brandenburg'],
    ['EI', 'Eichstätt in Bayern'],
    ['EIC', 'Eichsfeld in Thüringen'],
    ['EIL', 'Eisleben in Sachsen-Anhalt'],
    ['EIS', 'Eisenberg in Thüringen'],
    ['EL', 'Emsland / Meppen in Niedersachsen'],
    ['EM', 'Emmendingen in Baden-Württemberg'],
    ['EMD', 'Emden in Niedersachsen'],
    ['EMS', 'Rhein-Lahn-Kreis / Bad Ems in Rheinland-Pfalz'],
    ['EN', 'Ennepe-Ruhr-Kreis / Schwelm in Nordrhein-Westfalen'],
    ['ER', 'Erlangen in Bayern'],
    ['ERB', 'Odenwaldkreis / Erbach in Hessen'],
    ['ERH', 'Erlangen-Höchstadt in Bayern'],
    ['ES', 'Esslingen/Neckar in Baden-Württemberg'],
    ['ESA', 'Eisenach in Thüringen'],
    ['ESW', 'Werra-Meißner-Kreis / Eschwege in Hessen'],
    ['EU', 'Euskirchen in Nordrhein-Westfalen'],
    ['EW', 'Eberswalde in Brandenburg'],
    ['F', 'Frankfurt/Main in Hessen'],
    ['FB', 'Wetteraukreis / Friedberg in Hessen'],
    ['FD', 'Fulda in Hessen'],
    ['FDS', 'Freudenstadt in Baden-Württemberg'],
    ['FF', 'Frankfurt/Oder in Brandenburg'],
    ['FFB', 'Fürstenfeldbruck in Bayern'],
    ['FG', 'Freiberg in Sachsen'],
    ['FI', 'Finsterwalde in Brandenburg'],
    ['FL', 'Flensburg in Schleswig-Holstein'],
    ['FLÖ', 'Flöha in Sachsen'],
    ['FN', 'Bodenseekreis / Friedrichshafen in Baden-Württemberg'],
    ['FO', 'Forchheim in Bayern'],
    ['FOR', 'Forst in Brandenburg'],
    ['FR', 'Freiburg/Breisgau in Baden-Württemberg'],
    ['FRG', 'Freyung-Grafenau in Bayern'],
    ['FRI', 'Friesland / Jever in Niedersachsen'],
    ['FRW', 'Bad Freienwalde in Brandenburg'],
    ['FS', 'Freising in Bayern'],
    ['FT', 'Frankenthal/Pfalz in Rheinland-Pfalz'],
    ['FTL', 'Freital in Sachsen'],
    ['FÜ', 'Fürth in Bayern'],
    ['FW', 'Fürstenwalde in Brandenburg'],
    ['G', 'Gera in Thüringen'],
    ['GA', 'Gardelegen in Sachsen-Anhalt'],
    ['GAP', 'Garmisch-Partenkirchen in Bayern'],
    ['GC', 'Glauchau, Chemnitzer Land in Sachsen'],
    ['GDB', 'Gadebusch in Mecklenburg-Vorpommern'],
    ['GE', 'Gelsenkirchen in Nordrhein-Westfalen'],
    ['GER', 'Germersheim in Rheinland-Pfalz'],
    ['GF', 'Gifhorn in Niedersachsen'],
    ['GG', 'Groß-Gerau in Hessen'],
    ['GHA', 'Geithain in Sachsen'],
    ['GHC', 'Gräfenhainichen in Sachsen-Anhalt'],
    ['GI', 'Gießen in Hessen'],
    ['GL', 'Rheinisch-Bergischer Kreis / Bergisch Gladbach in Nordrhein-Westfalen'],
    ['GM', 'Oberbergischer Kreis / Gummersbach in Nordrhein-Westfalen'],
    ['GMN', 'Grimmen in Mecklenburg-Vorpommern'],
    ['GNT', 'Genthin in Sachsen-Anhalt'],
    ['GÖ', 'Göttingen in Niedersachsen'],
    ['GP', 'Göppingen in Baden-Württemberg'],
    ['GR', 'Görlitz in Sachsen'],
    ['GRH', 'Großenhain in Sachsen'],
    ['GRM', 'Grimma in Sachsen'],
    ['GRS', 'Gransee in Brandenburg'],
    ['GRZ', 'Greiz in Thüringen'],
    ['GS', 'Goslar in Niedersachsen'],
    ['GT', 'Gütersloh in Nordrhein-Westfalen'],
    ['GTH', 'Gotha in Thüringen'],
    ['GÜ', 'Güstrow in Mecklenburg-Vorpommern'],
    ['GUB', 'Guben in Brandenburg'],
    ['GVM', 'Grevesmühlen in Mecklenburg-Vorpommern'],
    ['GW', 'Greifswald in Mecklenburg-Vorpommern'],
    ['GZ', 'Günzburg in Bayern'],
    ['H', 'Hannover in Niedersachsen'],
    ['HA', 'Hagen/Westfalen in Nordrhein-Westfalen'],
    ['HAL', 'Halle/Saale in Sachsen-Anhalt'],
    ['HAM', 'Hamm/Westfalen in Nordrhein-Westfalen'],
    ['HAS', 'Haßberge / Haßfurt in Bayern'],
    ['HB', 'Hansestadt Bremen und Bremerhaven'],
    ['HBN', 'Hildburghausen in Thüringen'],
    ['HBS', 'Halberstadt in Sachsen-Anhalt'],
    ['HC', 'Hainichen in Sachsen'],
    ['HD', 'Rhein-Neckar-Kreis und Heidelberg in Baden-Württemberg'],
    ['HDH', 'Heidenheim/Brenz in Baden-Württemberg'],
    ['HDL', 'Haldensleben in Sachsen-Anhalt'],
    ['HE', 'Helmstedt in Niedersachsen'],
    ['HEF', 'Bad Hersfeld-Rotenburg in Hessen'],
    ['HEI', 'Dithmarschen / Heide in Schleswig-Holstein'],
    ['HEL', 'Hessen, Landesregierung und Landtag'],
    ['HER', 'Herne in Nordrhein-Westfalen'],
    ['HET', 'Hettstedt in Sachsen-Anhalt'],
    ['HF', 'Herford in Nordrhein-Westfalen'],
    ['HG', 'Hochtaunuskreis / Bad Homburg in Hessen'],
    ['HGN', 'Hagenow in Mecklenburg-Vorpommern'],
    ['HGW', 'Hansestadt Greifswald in Mecklenburg-Vorpommern'],
    ['HH', 'Hansestadt Hamburg'],
    ['HHM', 'Hohenmölsen in Sachsen-Anhalt'],
    ['HI', 'Hildesheim in Niedersachsen'],
    ['HIG', 'Heiligenstadt in Thüringen'],
    ['HL', 'Hansestadt Lübeck in Schleswig-Holstein'],
    ['HM', 'Hameln-Pyrmont in Niedersachsen'],
    ['HN', 'Heilbronn/Neckar in Baden-Württemberg'],
    ['HO', 'Hof/Saale in Bayern'],
    ['HOL', 'Holzminden in Niedersachsen'],
    ['HOM', 'Saar-Pfalz-Kreis / Homburg im Saarland'],
    ['HOT', 'Hohenstein-Ernstthal in Sachsen'],
    ['HP', 'Bergstraße / Heppenheim in Hessen'],
    ['HR', 'Schwalm-Eder-Kreis / Homberg in Hessen'],
    ['HRO', 'Hansestadt Rostock in Mecklenburg-Vorpommern'],
    ['HS', 'Heinsberg in Nordrhein-Westfalen'],
    ['HSK', 'Hochsauerlandkreis / Meschede in Nordrhein-Westfalen'],
    ['HST', 'Hansestadt Stralsund in Mecklenburg-Vorpommern'],
    ['HU', 'Hanau in Hessen'],
    ['HV', 'Havelberg in Sachsen-Anhalt'],
    ['HVL', 'Havelland in Brandenburg'],
    ['HWI', 'Hansestadt Wismar in Mecklenburg-Vorpommern'],
    ['HX', 'Höxter in Nordrhein-Westfalen'],
    ['HY', 'Hoyerswerda in Sachsen'],
    ['HZ', 'Herzberg in Brandenburg'],
    ['IGB', 'St. Ingbert im Saarland'],
    ['IK', 'Ilm-Kreis in Thüringen'],
    ['IL', 'Ilmenau in Thüringen'],
    ['IN', 'Ingolstadt/Donau in Bayern'],
    ['IZ', 'Itzehoe in Schleswig-Holstein'],
    ['J', 'Jena in Thüringen'],
    ['JB', 'Jüterbog in Brandenburg'],
    ['JE', 'Jessen in Sachsen-Anhalt'],
    ['JL', 'Jerichower Land in Sachsen-Anhalt'],
    ['K', 'Köln in Nordrhein-Westfalen'],
    ['KA', 'Karlsruhe in Baden-Württemberg'],
    ['KB', 'Waldeck-Frankenberg / Korbach in Hessen'],
    ['KC', 'Kronach in Bayern'],
    ['KE', 'Kempten/Allgäu in Bayern'],
    ['KEH', 'Kelheim in Bayern'],
    ['KF', 'Kaufbeuren in Bayern'],
    ['KG', 'Bad Kissingen in Bayern'],
    ['KH', 'Bad Kreuznach in Rheinland-Pfalz'],
    ['KI', 'Kiel in Schleswig-Holstein'],
    ['KIB', 'Donnersberg-Kreis / Kirchheimbolanden in Rheinland-Pfalz'],
    ['KL', 'Kaiserslautern in Rheinland-Pfalz'],
    ['KLE', 'Kleve in Nordrhein-Westfalen'],
    ['KLZ', 'Klötze in Sachsen-Anhalt'],
    ['KM', 'Kamenz in Sachsen'],
    ['KN', 'Konstanz in Baden-Württemberg'],
    ['KO', 'Koblenz in Rheinland-Pfalz'],
    ['KÖT', 'Köthen in Sachsen-Anhalt'],
    ['KR', 'Krefeld in Nordrhein-Westfalen'],
    ['KS', 'Kassel in Hessen'],
    ['KT', 'Kitzingen in Bayern'],
    ['KU', 'Kulmbach in Bayern'],
    ['KÜN', 'Hohenlohe-Kreis / Künzelsau in Baden-Württemberg'],
    ['KUS', 'Kusel in Rheinland-Pfalz'],
    ['KW', 'Königs Wusterhausen in Brandenburg'],
    ['KY', 'Kyritz in Brandenburg'],
    ['KYF', 'Kyffhäuserkreis in Thüringen'],
    ['L', 'Leipzig in Sachsen'],
    ['LA', 'Landshut in Bayern'],
    ['LAU', 'Nürnberger Land / Lauf in Bayern'],
    ['LB', 'Ludwigsburg in Baden-Württemberg'],
    ['LBS', 'Lobenstein in Thüringen'],
    ['LBZ', 'Lübz in Mecklenburg-Vorpommern'],
    ['LC', 'Luckau in Sachsen'],
    ['LD', 'Landau/Pfalz in Rheinland-Pfalz'],
    ['LDK', 'Lahn-Dill-Kreis / Wetzlar in Hessen'],
    ['LDS', 'Dahme-Spreewald in Brandenburg'],
    ['LER', 'Leer/Ostfriesland in Niedersachsen'],
    ['LEV', 'Leverkusen in Nordrhein-Westfalen'],
    ['LG', 'Lüneburg in Niedersachsen'],
    ['LI', 'Lindau/Bodensee in Bayern'],
    ['LIB', 'Bad Liebenwerda in Brandenburg'],
    ['LIF', 'Lichtenfels in Bayern'],
    ['LIP', 'Lippe / Detmold in Nordrhein-Westfalen'],
    ['LL', 'Landsberg/Lech in Bayern'],
    ['LM', 'Limburg-Weilburg in Hessen'],
    ['LN', 'Lübben in Brandenburg'],
    ['LÖ', 'Lörrach in Baden-Württemberg'],
    ['LÖB', 'Löbau in Sachsen'],
    ['LOS', 'Oder-Spree in Brandenburg'],
    ['LSA', 'Sachsen-Anhalt, Landesregierung und Landtag'],
    ['LSN', 'Sachsen, Landesregierung und Landtag'],
    ['LSZ', 'Bad Langensalza in Thüringen'],
    ['LU', 'Ludwigshafen/Rhein in Rheinland-Pfalz'],
    ['LUK', 'Luckenwalde in Brandenburg'],
    ['LWL', 'Ludwigslust in Mecklenburg-Vorpommern'],
    ['M', 'München in Bayern'],
    ['MA', 'Mannheim in Baden-Württemberg'],
    ['MAB', 'Marienberg in Sachsen'],
    ['MB', 'Miesbach in Bayern'],
    ['MC', 'Malchin in Mecklenburg-Vorpommern'],
    ['MD', 'Magdeburg in Sachsen-Anhalt'],
    ['ME', 'Mettmann in Nordrhein-Westfalen'],
    ['MEI', 'Meißen in Sachsen'],
    ['MEK', 'Mittlerer Erzgebirgskreis in Sachsen'],
    ['MER', 'Merseburg in Sachsen-Anhalt'],
    ['MG', 'Mönchengladbach in Nordrhein-Westfalen'],
    ['MGN', 'Meiningen in Thüringen'],
    ['MH', 'Mülheim/Ruhr in Nordrhein-Westfalen'],
    ['MHL', 'Mühlhausen in Thüringen'],
    ['MI', 'Minden-Lübbecke in Nordrhein-Westfalen'],
    ['MIL', 'Miltenberg in Bayern'],
    ['MK', 'Märkischer Kreis / Lüdenscheid in Nordrhein-Westfalen'],
    ['MKK', 'Main-Kinzig-Kreis in Hessen'],
    ['ML', 'Mansfelder Land in Sachsen-Anhalt'],
    ['MM', 'Memmingen in Bayern'],
    ['MN', 'Unterallgäu / Mindelheim in Bayern'],
    ['MOL', 'Märkisch-Oderland in Brandenburg'],
    ['MOS', 'Neckar-Odenwald-Kreis / Mosbach in Baden-Württemberg'],
    ['MQ', 'Merseburg-Querfurt in Sachsen-Anhalt'],
    ['MR', 'Marburg-Biedenkopf in Hessen'],
    ['MS', 'Münster/Westfalen in Nordrhein-Westfalen'],
    ['MSP', 'Main-Spessart-Kreis / Karlstadt in Bayern'],
    ['MST', 'Mecklenburg-Strelitz in Mecklenburg-Vorpommern'],
    ['MTK', 'Main-Taunus-Kreis / Hofheim in Hessen'],
    ['MÜ', 'Mühldorf am Inn in Bayern'],
    ['MÜR', 'Müritz in Mecklenburg-Vorpommern'],
    ['MVL', 'Mecklenburg-Vorpommern, Landesregierung und Landtag'],
    ['MW', 'Mittweida in Sachsen'],
    ['MYK', 'Mayen-Koblenz in Rheinland-Pfalz'],
    ['MZ', 'Mainz-Bingen und Mainz in Rheinland-Pfalz'],
    ['MZG', 'Merzig-Wadern im Saarland'],
    ['N', 'Nürnberg in Bayern'],
    ['NAU', 'Nauen in Brandenburg'],
    ['NB', 'Neubrandenburg in Mecklenburg-Vorpommern'],
    ['ND', 'Neuburg-Schrobenhausen in Bayern'],
    ['NDH', 'Nordhausen in Thüringen'],
    ['NE', 'Neuss in Nordrhein-Westfalen'],
    ['NEA', 'Neustadt-Bad Windsheim in Bayern'],
    ['NEB', 'Nebra/Unstrut in Sachsen-Anhalt'],
    ['NES', 'Rhön-Grabfeld / Bad Neustadt in Bayern'],
    ['NEW', 'Neustadt/Waldnaab in Bayern'],
    ['NF', 'Nordfriesland / Husum in Schleswig-Holstein'],
    ['NH', 'Neuhaus/Rennsteig in Thüringen'],
    ['NI', 'Nienburg/Weser in Niedersachsen'],
    ['NK', 'Neunkirchen im Saarland'],
    ['NL', 'Niedersachsen, Landesregierung und Landtag'],
    ['NM', 'Neumarkt/Oberpfalz in Bayern'],
    ['NMB', 'Naumburg/Saale in Sachsen-Anhalt'],
    ['NMS', 'Neumünster in Schleswig-Holstein'],
    ['NOH', 'Grafschaft Bentheim / Nordhorn in Niedersachsen'],
    ['NOL', 'Niederschlesischer Oberlausitzkreis in Sachsen'],
    ['NOM', 'Northeim in Niedersachsen'],
    ['NP', 'Neuruppin in Brandenburg'],
    ['NR', 'Neuwied/Rhein in Rheinland-Pfalz'],
    ['NRW', 'Nordrhein-Westfalen, Landesregierung und Landtag'],
    ['NU', 'Neu-Ulm in Bayern'],
    ['NVP', 'Nordvorpommern in Mecklenburg-Vorpommern'],
    ['NW', 'Neustadt/Weinstraße in Rheinland-Pfalz'],
    ['NWM', 'Nordwestmecklenburg in Mecklenburg-Vorpommern'],
    ['NY', 'Niesky in Sachsen'],
    ['NZ', 'Neustrelitz in Mecklenburg-Vorpommern'],
    ['OA', 'Oberallgäu / Sonthofen in Bayern'],
    ['OAL', 'Ostallgäu / Marktoberdorf in Bayern'],
    ['OB', 'Oberhausen in Nordrhein-Westfalen'],
    ['OBG', 'Osterburg in Sachsen-Anhalt'],
    ['OC', 'Oschersleben in Sachsen-Anhalt'],
    ['OD', 'Stormarn / Bad Oldesloe in Schleswig-Holstein'],
    ['OE', 'Olpe in Nordrhein-Westfalen'],
    ['OF', 'Offenbach/Main in Hessen'],
    ['OG', 'Ortenaukreis / Offenburg in Baden-Württemberg'],
    ['OH', 'Ostholstein / Eutin in Schleswig-Holstein'],
    ['OHA', 'Osterode/Harz in Niedersachsen'],
    ['OHV', 'Oberhavel in Brandenburg'],
    ['OHZ', 'Osterholz-Scharmbeck in Niedersachsen'],
    ['OK', 'Ohre-Kreis in Sachsen-Anhalt'],
    ['OL', 'Oldenburg in Niedersachsen'],
    ['OPR', 'Ostprignitz-Ruppin in Brandenburg'],
    ['OR', 'Oranienburg in Brandenburg'],
    ['OS', 'Osnabrück in Niedersachsen'],
    ['OSL', 'Oberspreewald-Lausitz in Brandenburg'],
    ['OVL', 'Obervogtland in Sachsen'],
    ['OVP', 'Ostvorpommern in Mecklenburg-Vorpommern'],
    ['OZ', 'Oschatz in Sachsen'],
    ['P', 'Potsdam in Brandenburg'],
    ['PA', 'Passau in Bayern'],
    ['PAF', 'Pfaffenhofen/Ilm in Bayern'],
    ['PAN', 'Rottal-Inn / Pfarrkirchen in Bayern'],
    ['PB', 'Paderborn in Nordrhein-Westfalen'],
    ['PCH', 'Parchim in Mecklenburg-Vorpommern'],
    ['PE', 'Peine in Niedersachsen'],
    ['PER', 'Perleberg in Brandenburg'],
    ['PF', 'Enzkreis und Pforzheim in Baden-Württemberg'],
    ['PI', 'Pinneberg in Schleswig-Holstein'],
    ['PIR', 'Pirna, Sächsische Schweiz in Sachsen'],
    ['PK', 'Pritzwalk in Brandenburg'],
    ['PL', 'Plauen in Sachsen'],
    ['PLÖ', 'Plön in Schleswig-Holstein'],
    ['PM', 'Potsdam-Mittelmark in Brandenburg'],
    ['PN', 'Pössneck in Thüringen'],
    ['PR', 'Prignitz / Perleberg in Brandenburg'],
    ['PS', 'Pirmasens in Rheinland-Pfalz'],
    ['PW', 'Pasewalk in Mecklenburg-Vorpommern'],
    ['PZ', 'Prenzlau in Brandenburg'],
    ['QFT', 'Querfurt in Sachsen-Anhalt'],
    ['QLB', 'Quedlinburg in Sachsen-Anhalt'],
    ['R', 'Regensburg in Bayern'],
    ['RA', 'Rastatt in Baden-Württemberg'],
    ['RC', 'Reichenbach/Vogtland in Sachsen'],
    ['RD', 'Rendsburg-Eckernförde in Schleswig-Holstein'],
    ['RDG', 'Ribnitz-Damgarten in Mecklenburg-Vorpommern'],
    ['RE', 'Recklinghausen in Nordrhein-Westfalen'],
    ['REG', 'Regen in Bayern'],
    ['RG', 'Riesa-Großenhain in Sachsen'],
    ['RH', 'Roth in Bayern'],
    ['RIE', 'Riesa in Sachsen'],
    ['RL', 'Rochlitz in Sachsen'],
    ['RM', 'Röbel/Müritz in Mecklenburg-Vorpommern'],
    ['RN', 'Rathenow in Brandenburg'],
    ['RO', 'Rosenheim in Bayern'],
    ['ROS', 'Rostock/Landkreis in Mecklenburg-Vorpommern'],
    ['ROW', 'Rotenburg/Wümme in Niedersachsen'],
    ['RP', 'Rhein-Pfalz-Kreis in Rheinland-Pfalz'],
    ['RPL', 'Rheinland-Pfalz, Landesregierung und Landtag'],
    ['RS', 'Remscheid in Nordrhein-Westfalen'],
    ['RSL', 'Roßlau/Elbe in Sachsen-Anhalt'],
    ['RT', 'Reutlingen in Baden-Württemberg'],
    ['RU', 'Rudolstadt in Thüringen'],
    ['RÜD', 'Rheingau-Taunus-Kreis / Rüdesheim in Hessen'],
    ['RÜG', 'Rügen / Bergen in Mecklenburg-Vorpommern'],
    ['RV', 'Ravensburg in Baden-Württemberg'],
    ['RW', 'Rottweil in Baden-Württemberg'],
    ['RZ', 'Herzogtum Lauenburg / Ratzeburg in Schleswig-Holstein'],
    ['S', 'Stuttgart in Baden-Württemberg'],
    ['SAD', 'Schwandorf in Bayern'],
    ['SAL', 'Saarland, Landesregierung und Landtag'],
    ['SAW', 'Altmarkkreis Salzwedel in Sachsen-Anhalt'],
    ['SB', 'Saarbrücken im Saarland'],
    ['SBG', 'Strasburg in Mecklenburg-Vorpommern'],
    ['SBK', 'Schönebeck/Elbe in Sachsen-Anhalt'],
    ['SC', 'Schwabach in Bayern'],
    ['SCZ', 'Schleiz in Thüringen'],
    ['SDH', 'Sondershausen in Thüringen'],
    ['SDL', 'Stendal in Sachsen-Anhalt'],
    ['SDT', 'Schwedt/Oder in Brandenburg'],
    ['SE', 'Bad Segeberg in Schleswig-Holstein'],
    ['SEB', 'Sebnitz in Sachsen'],
    ['SEE', 'Seelow in Brandenburg'],
    ['SFA', 'Soltau-Fallingbostel in Niedersachsen'],
    ['SFB', 'Senftenberg in Brandenburg'],
    ['SFT', 'Staßfurt in Sachsen-Anhalt'],
    ['SG', 'Solingen in Nordrhein-Westfalen'],
    ['SGH', 'Sangerhausen in Sachsen-Anhalt'],
    ['SH', 'Schleswig-Holstein, Landesregierung und Landtag'],
    ['SHA', 'Schwäbisch Hall in Baden-Württemberg'],
    ['SHG', 'Schaumburg / Stadthagen in Niedersachsen'],
    ['SHK', 'Saale-Holzlandkreis in Thüringen'],
    ['SHL', 'Suhl in Thüringen'],
    ['SI', 'Siegen-Wittgenstein in Nordrhein-Westfalen'],
    ['SIG', 'Sigmaringen in Baden-Württemberg'],
    ['SIM', 'Rhein-Hunsrück-Kreis / Simmern in Rheinland-Pfalz'],
    ['SK', 'Saalkreis / Halle in Sachsen-Anhalt'],
    ['SL', 'Schleswig-Flensburg in Schleswig-Holstein'],
    ['SLF', 'Saalfeld-Rudolstadt in Thüringen'],
    ['SLN', 'Schmölln in Thüringen'],
    ['SLS', 'Saarlouis im Saarland'],
    ['SLZ', 'Bad Salzungen in Thüringen'],
    ['SM', 'Schmalkalden-Meiningen in Thüringen'],
    ['SN', 'Schwerin in Mecklenburg-Vorpommern'],
    ['SO', 'Soest in Nordrhein-Westfalen'],
    ['SOK', 'Saale-Orla-Kreis in Thüringen'],
    ['SÖM', 'Sömmerda in Thüringen'],
    ['SON', 'Sonneberg in Thüringen'],
    ['SP', 'Speyer in Rheinland-Pfalz'],
    ['SPB', 'Spremberg in Brandenburg'],
    ['SPN', 'Spree-Neiße in Brandenburg'],
    ['SR', 'Straubing-Bogen in Bayern'],
    ['SRB', 'Strausberg in Brandenburg'],
    ['SRO', 'Stadtroda in Thüringen'],
    ['ST', 'Steinfurt in Nordrhein-Westfalen'],
    ['STA', 'Starnberg in Bayern'],
    ['STB', 'Sternberg in Mecklenburg-Vorpommern'],
    ['STD', 'Stade in Niedersachsen'],
    ['STL', 'Stollberg in Sachsen'],
    ['SU', 'Rhein-Sieg-Kreis / Siegburg in Nordrhein-Westfalen'],
    ['SÜW', 'Südliche Weinstraße / Landau in Rheinland-Pfalz'],
    ['SW', 'Schweinfurt in Bayern'],
    ['SZ', 'Salzgitter in Niedersachsen'],
    ['SZB', 'Schwarzenberg in Sachsen'],
    ['TBB', 'Main-Tauber-Kreis / Tauberbischofsheim in Baden-Württemberg'],
    ['TET', 'Teterow in Mecklenburg-Vorpommern'],
    ['TF', 'Teltow-Fläming in Brandenburg'],
    ['TG', 'Torgau in Sachsen'],
    ['THL', 'Thüringen, Landesregierung und Landtag'],
    ['THW', 'Technisches Hilfswerk'],
    ['TIR', 'Tirschenreuth in Bayern'],
    ['TO', 'Torgau-Oschatz in Sachsen'],
    ['TÖL', 'Bad Tölz-Wolfratshausen in Bayern'],
    ['TP', 'Templin in Brandenburg'],
    ['TR', 'Trier-Saarburg in Rheinland-Pfalz'],
    ['TS', 'Traunstein in Bayern'],
    ['TÜ', 'Tübingen in Baden-Württemberg'],
    ['TUT', 'Tuttlingen in Baden-Württemberg'],
    ['UE', 'Uelzen in Niedersachsen'],
    ['UEM', 'Ueckermünde in Mecklenburg-Vorpommern'],
    ['UER', 'Uecker-Randow in Mecklenburg-Vorpommern'],
    ['UH', 'Unstrut-Hainich-Kreis in Thüringen'],
    ['UL', 'Alb-Donau-Kreis und Ulm in Baden-Württemberg'],
    ['UM', 'Uckermark in Brandenburg'],
    ['UN', 'Unna in Nordrhein-Westfalen'],
    ['V', 'Vogtlandkreis / Plauen in Sachsen'],
    ['VB', 'Vogelsbergkreis / Lauterbach in Hessen'],
    ['VEC', 'Vechta in Niedersachsen'],
    ['VER', 'Verden/Aller in Niedersachsen'],
    ['VIE', 'Viersen in Nordrhein-Westfalen'],
    ['VK', 'Völklingen im Saarland'],
    ['VS', 'Schwarzwald-Baar-Kreis / Villingen-Schwenningen in Baden-Württemberg'],
    ['W', 'Wuppertal in Nordrhein-Westfalen'],
    ['WAF', 'Warendorf in Nordrhein-Westfalen'],
    ['WAK', 'Wartburgkreis in Thüringen'],
    ['WB', 'Wittenberg in Sachsen-Anhalt'],
    ['WBS', 'Worbis in Thüringen'],
    ['WDA', 'Werdau in Sachsen'],
    ['WE', 'Weimar in Thüringen'],
    ['WEN', 'Weiden/Oberpfalz in Bayern'],
    ['WES', 'Wesel in Nordrhein-Westfalen'],
    ['WF', 'Wolfenbüttel in Niedersachsen'],
    ['WHV', 'Wilhelmshaven in Niedersachsen'],
    ['WI', 'Wiesbaden in Hessen'],
    ['WIL', 'Bernkastel-Wittlich in Rheinland-Pfalz'],
    ['WIS', 'Wismar in Mecklenburg-Vorpommern'],
    ['WK', 'Wittstock in Brandenburg'],
    ['WL', 'Harburg / Winsen in Niedersachsen'],
    ['WLG', 'Wolgast in Mecklenburg-Vorpommern'],
    ['WM', 'Weilheim-Schongau in Bayern'],
    ['WMS', 'Wolmirstedt in Sachsen-Anhalt'],
    ['WN', 'Rems-Murr-Kreis / Waiblingen in Baden-Württemberg'],
    ['WND', 'St. Wendel im Saarland'],
    ['WO', 'Worms in Rheinland-Pfalz'],
    ['WOB', 'Wolfsburg in Niedersachsen'],
    ['WR', 'Wernigerode in Sachsen-Anhalt'],
    ['WRN', 'Waren/Müritz in Mecklenburg-Vorpommern'],
    ['WSF', 'Weißenfels in Sachsen-Anhalt'],
    ['WST', 'Ammerland / Westerstede in Niedersachsen'],
    ['WSW', 'Weißwasser in Sachsen'],
    ['WT', 'Waldshut-Tiengen in Baden-Württemberg'],
    ['WTM', 'Wittmund in Niedersachsen'],
    ['WÜ', 'Würzburg in Bayern'],
    ['WUG', 'Weißenburg-Gunzenhausen in Bayern'],
    ['WUN', 'Wunsiedel in Bayern'],
    ['WUR', 'Wurzen in Sachsen'],
    ['WW', 'Westerwald / Montabaur in Rheinland-Pfalz'],
    ['WZL', 'Wanzleben in Sachsen-Anhalt'],
    ['X', 'Bundeswehr, NATO-Hauptquartiere'],
    ['Y', 'Bundeswehr'],
    ['Z', 'Zwickauer Land in Sachsen'],
    ['ZE', 'Zerbst in Sachsen-Anhalt'],
    ['ZI', 'Zittau, Oberlausitzkreis in Sachsen'],
    ['ZP', 'Zschopau in Sachsen'],
    ['ZR', 'Zeulenroda in Thüringen'],
    ['ZS', 'Zossen in Brandenburg'],
    ['ZW', 'Zweibrücken in Rheinland-Pfalz'],
    ['ZZ', 'Zeitz in Sachsen-Anhalt']
])

/**
 * Ermittelt den Landkreis/Stadt anhand des Kennzeichen-Präfix.
 * @param {string} licensePlate - Kennzeichen (z.B. "B-AB 1234")
 * @returns {string|null} Landkreis/Stadt oder null
 */
export function getDistrictByPlate(licensePlate) {
    if (!licensePlate) return null
    const prefix = licensePlate.trim().split('-')[0].toUpperCase()
    if (!prefix) return null
    return kennzeichenMap.get(prefix) || null
}
