-- Minimal auth database bootstrap for fresh MotorDesk installations.
-- Values such as the admin login and company DB password are injected by psql
-- variables from scripts/bootstrap-fresh.sh.

CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL,
    password text NOT NULL,
    name text,
    email text,
    active boolean NOT NULL DEFAULT true,
    itime timestamp without time zone NOT NULL DEFAULT now(),
    mtime timestamp without time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS auth_user_login_key
    ON auth."user" (login);

CREATE TABLE IF NOT EXISTS auth.clients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    dbhost text NOT NULL DEFAULT 'db',
    dbport text NOT NULL DEFAULT '5432',
    dbname text NOT NULL,
    dbuser text NOT NULL,
    dbpasswd text NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    itime timestamp without time zone NOT NULL DEFAULT now(),
    mtime timestamp without time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS auth_clients_name_key
    ON auth.clients (name);

CREATE TABLE IF NOT EXISTS auth.clients_users (
    client_id integer NOT NULL REFERENCES auth.clients(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, user_id)
);

CREATE TABLE IF NOT EXISTS auth."group" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    itime timestamp without time zone NOT NULL DEFAULT now(),
    mtime timestamp without time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS auth_group_name_key
    ON auth."group" (name);

CREATE TABLE IF NOT EXISTS auth.user_group (
    user_id integer NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES auth."group"(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS auth.clients_groups (
    client_id integer NOT NULL REFERENCES auth.clients(id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES auth."group"(id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, group_id)
);

CREATE TABLE IF NOT EXISTS auth.group_rights (
    group_id integer NOT NULL REFERENCES auth."group"(id) ON DELETE CASCADE,
    "right" text NOT NULL,
    granted boolean NOT NULL DEFAULT true,
    PRIMARY KEY (group_id, "right")
);

CREATE TABLE IF NOT EXISTS auth.user_config (
    user_id integer NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
    cfg_key text NOT NULL,
    cfg_value text,
    PRIMARY KEY (user_id, cfg_key)
);

CREATE TABLE IF NOT EXISTS auth.session_oserp (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id text PRIMARY KEY,
    user_id integer NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
    client_id integer NOT NULL REFERENCES auth.clients(id) ON DELETE CASCADE,
    active timestamp without time zone DEFAULT now(),
    remember_me boolean NOT NULL DEFAULT false
);

CREATE OR REPLACE FUNCTION auth.cleanup_session_oserp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM auth.session_oserp
    WHERE active < NOW() - INTERVAL '120 hours';
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_cleanup_session_oserp ON auth.session_oserp;
CREATE TRIGGER trigger_cleanup_session_oserp
AFTER INSERT OR UPDATE
ON auth.session_oserp
FOR EACH STATEMENT
EXECUTE FUNCTION auth.cleanup_session_oserp();

DROP TABLE IF EXISTS pg_temp.motordesk_bootstrap_context;

CREATE TEMP TABLE motordesk_bootstrap_context AS
WITH seeded_user AS (
    INSERT INTO auth."user" (login, password, name, active, mtime)
    VALUES (:'admin_login', :'admin_hash', :'admin_name', true, now())
    ON CONFLICT (login) DO UPDATE SET
        password = EXCLUDED.password,
        name = EXCLUDED.name,
        active = true,
        mtime = now()
    RETURNING id
),
seeded_client AS (
    INSERT INTO auth.clients (
        name,
        dbhost,
        dbport,
        dbname,
        dbuser,
        dbpasswd,
        is_default,
        mtime
    )
    VALUES (
        :'client_name',
        'db',
        '5432',
        :'company_db',
        :'db_user',
        :'db_pass',
        true,
        now()
    )
    ON CONFLICT (name) DO UPDATE SET
        dbhost = EXCLUDED.dbhost,
        dbport = EXCLUDED.dbport,
        dbname = EXCLUDED.dbname,
        dbuser = EXCLUDED.dbuser,
        dbpasswd = EXCLUDED.dbpasswd,
        is_default = true,
        mtime = now()
    RETURNING id
),
seeded_group AS (
    INSERT INTO auth."group" (name, mtime)
    VALUES ('Administratoren', now())
    ON CONFLICT (name) DO UPDATE SET
        name = EXCLUDED.name,
        mtime = now()
    RETURNING id
)
SELECT
    seeded_user.id AS user_id,
    seeded_client.id AS client_id,
    seeded_group.id AS group_id
FROM seeded_user
CROSS JOIN seeded_client
CROSS JOIN seeded_group;

UPDATE auth.clients
SET is_default = false,
    mtime = now()
WHERE id <> (SELECT client_id FROM pg_temp.motordesk_bootstrap_context);

INSERT INTO auth.clients_users (client_id, user_id)
SELECT client_id, user_id
FROM pg_temp.motordesk_bootstrap_context
ON CONFLICT DO NOTHING;

INSERT INTO auth.user_group (user_id, group_id)
SELECT user_id, group_id
FROM pg_temp.motordesk_bootstrap_context
ON CONFLICT DO NOTHING;

INSERT INTO auth.clients_groups (client_id, group_id)
SELECT client_id, group_id
FROM pg_temp.motordesk_bootstrap_context
ON CONFLICT DO NOTHING;

INSERT INTO auth.group_rights (group_id, "right", granted)
SELECT ctx.group_id, rights."right", true
FROM pg_temp.motordesk_bootstrap_context ctx
CROSS JOIN (
    VALUES
        ('admin'),
        ('special_access'),
        ('customer_vendor_edit'),
        ('customer_vendor_all_edit'),
        ('invoice_edit'),
        ('sales_order_edit'),
        ('sales_quotation_edit'),
        ('sales_delivery_order_edit')
) AS rights("right")
ON CONFLICT (group_id, "right") DO UPDATE SET
    granted = EXCLUDED.granted;

INSERT INTO auth.user_config (user_id, cfg_key, cfg_value)
SELECT ctx.user_id, cfg.cfg_key, cfg.cfg_value
FROM pg_temp.motordesk_bootstrap_context ctx
CROSS JOIN (
    VALUES
        ('language', 'de'),
        ('theme', 'dark')
) AS cfg(cfg_key, cfg_value)
ON CONFLICT (user_id, cfg_key) DO UPDATE SET
    cfg_value = EXCLUDED.cfg_value;
